### PR TITLE
CW-kebabize 

### PR DESCRIPTION
**Pull request by aepaysinger**
big O: O(1) : The function has one task

### CODE REVIEW

**Comment by W-Ely** [comment]
> big O: O(1) : The function has one task

This is incorrect, tell me why.

**Comment by aepaysinger** [comment]
big O = O(n)
not O(1), it goes off of worst case. with the if else blocks its not only doing one thing.

**Comment by W-Ely** [comment]
> big O = O(n)

and
> it goes off of worst case.

^-- yes

>  with the if else blocks its not only doing one thing.

Has nothing to do with the if/else block

Why is this O(n).

**Comment by W-Ely** [comment]
> Linear time: 1 series operation for each item that is passed in.

What item(s) are being passed in?  Is it one thing or many?  How are you treating what is being passed in.

**Comment by aepaysinger** [comment]
a single string is being passed in. one item is being passed in. then each character of the string goes through the for loop.

**Comment by W-Ely** [comment]
> a single string

I think that this isn't correct. While technically maybe.  You are using this string as a collection of characters.  A string isn't one thing. It's a container of bytes.

So it's O(n) because as the string gets longer (containing more characters) the duration increases linearly.

**Comment by aepaysinger** [comment]
okay so it is O(n) and it is this because as the input size gets bigger the run time increases and it is also doing 1 series of operations?

**Review by W-Ely — APPROVED** [review]

**Pull request merged**
