### PR TITLE
CW sudokue board validator

### PR DESCRIPTION
**Pull request by aepaysinger**
having issues with the test for the check_sections method. I ran into a recursion error. i know we have talked about this before but I can't remember how to handle the issue

### CODE REVIEW

**Comment by W-Ely** [comment]
> I ran into a recursion error.

What does `recursion` mean?  Show me the line(s) of code that recursively calls itself.

**Comment by aepaysinger** [comment]
I call the function on line 59 but not sure why it is calling itself
multiple times

**Comment by aepaysinger** [comment]
Nevermind! I just realized what I did. I didn't use the .notation so it's
just calling over and over. I'll fix it when I get home

**Comment by W-Ely** [comment]
> but not sure why it is calling itself multiple times

If you don't see the function calling another function that calls itself, it isn't.

> Nevermind! I just realized what I did. I didn't use the .notation so it's
just calling over and over. I'll fix it when I get home

This is incorrect.

**Comment by W-Ely** [comment]
```python
def test_sudoku_check_sections():
    # .........
    assert test_sudoku_check_sections() == False
```

`assert test_sudoku_check_sections() ...` is invoking which function?

**Comment by aepaysinger** [comment]
It's calling test_sudokue_get_get sections but what I want is it to assert
sudoku_result.get_sections() == False

**Comment by W-Ely** [comment]
> It's calling test_sudokue_get_get

Right so it is invoking itself, the test function's name is `test_sudoku_check_sections` so calling `test_sudoku_check_sections()` causes the test to call itself over and over.

**Review by W-Ely — APPROVED** [review]

**Pull request merged**
